fpath=(
  /usr/local/share/zsh-completions
  /usr/local/share/zsh/site-functions
  $fpath
)
# OH MY ZSH STUFF BELOW
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kolo"
# DISABLE_AUTO_UPDATE="true"
plugins=(git hub)
source $ZSH/oh-my-zsh.sh

autoload -Uz compinit && compinit
zmodload -i zsh/complist
setopt completeinword

unset MAILCHECK
ulimit -S -c 0
umask 0022

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export EDITOR="vim"
export DEFAULT_USER="mark.turner"

export GOPATH=$HOME
export GOROOT=$HOME/code/go
export PATH=$PATH:$HOME/mygo/bin
export PATH=$HOME/code/go/bin:$PATH
export HISTSIZE=50000
export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"

export VIRTUALENV_DISTRIBUTE=true
export PIP_VIRTUALENV_BASE=$HOME/.virtualenvs
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

alias be="nocorrect bundle exec"
alias http="nocorrect http"
alias love="/Applications/love.app/Contents/MacOS/love"
alias vi="nvim"
alias vim="nvim"

alias e='emacsclient -t'
alias ec='emacsclient -c'

if which hub > /dev/null; then eval "$(hub alias -s)"; fi

export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/Applications/Postgres.app/Contents/Versions/9.4/bin:$PATH"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

for alias in $HOME/.aliases/*; do
  . $alias
done

export NVM_DIR="/Users/mark.turner/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

cdpath=(~/code/heroku $GOPATH/src)

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/mark.turner/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/mark.turner/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/mark.turner/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/mark.turner/Downloads/google-cloud-sdk/completion.zsh.inc'
fi
